version: '3'

services:
  web:
    image: python:3.9
    depends_on:
      - db
    volumes:
      - .:/opt/shaggy-axel
    container_name: shaggy-axel-web
    ports:
      - "0.0.0.0:8689:8000"
    env_file: .env
    working_dir: /opt/shaggy-axel
    command: /bin/bash -c 'scripts/run_server.sh'
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: shaggy-axel-db
    env_file: .env


volumes:
  postgres_data:
