# Generated by Django 3.2.6 on 2021-12-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default/profile_photo', upload_to='blog', verbose_name='Image'),
        ),
    ]
