# Generated by Django 3.2.6 on 2021-12-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default/Ruslan\\ Korneev.PNG', upload_to='blog', verbose_name='Image'),
        ),
    ]
