# Generated by Django 3.2.6 on 2021-09-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(to='resume.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resume.skillcategory'),
        ),
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(choices=[('BS', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BFA', 'Bachelor of Fine Arts'), ('BBA', 'Bachelor of Business Administration'), ('MS', 'Master of Science'), ('MBA', 'Master of Business Administration'), ('MFA', 'Master of Fine Arts'), ('PHD', 'Ph.D.')], max_length=100, verbose_name='Grade'),
        ),
    ]
